n_timesteps: !!float 10e4
policy: 'MlpPolicy'
env: 'CartPole-v0'
learning_rate: !!float 2.3e-3
batch_size: 64
buffer_size: 100000
learning_starts: 100
gamma: 0.99
target_update_interval: 500
train_freq: 256
gradient_steps: -1
exploration_fraction: 0.16
exploration_final_eps: 0.04
policy_kwargs: "dict(net_arch=[256, 256])"
